name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.3
  firebase_auth_platform_interface: ^7.4.8
  cloud_firestore: ^5.4.5
  sorter: ^0.0.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  mailer: ^6.2.0
  url_launcher: ^6.3.1
  provider: ^6.1.2
  go_router: ^14.6.0
  image_picker: ^1.1.2
  firebase_storage: ^12.3.6
  cloudinary: ^1.2.0
  image_picker_windows: ^0.2.1+1
  shared_preferences: ^2.3.3
  cached_network_image: ^3.4.1
  flutter_context_menu: ^0.2.0
  defer_pointer: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/
  fonts:
    - family: ChatFont
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
